# app.yaml - Configuración para Google App Engine

# Elige el runtime de Python que coincida con tu entorno de desarrollo
runtime: python310 # O python311, python312, etc.

# Las variables de entorno que tu aplicación necesita para funcionar.
# Estas se cargan de forma segura desde Google Secret Manager.
env_variables:
  # --- Secretos ---
  # Formato: projects/PROJECT_ID/secrets/SECRET_NAME/versions/latest
  SECRET_KEY: "projects/supercolegios/secrets/django_secret_key/versions/latest"
  
  # CORRECCIÓN: Se apunta a una versión específica del secreto para asegurar que se usa la contraseña correcta.
  # ¡IMPORTANTE! Reemplaza el '5' con el número de la última versión que creaste en Secret Manager.
  DB_PASSWORD: 'T6\T%$:b1T&)VCG('
  
  GCS_CREDENTIALS: "projects/supercolegios/secrets/gcs_credentials/versions/latest"

  # --- Configuración de la Base de Datos ---
  # El nombre de conexión de tu instancia de Cloud SQL.
  # Puedes encontrarlo en la página de detalles de tu instancia en la consola de Google Cloud.
  CLOUD_SQL_CONNECTION_NAME: "supercolegios:us-central1:mcolegio-db-prod"
  DB_NAME: "supercolegios_db"
  DB_USER: "postgres" # O el usuario que hayas configurado

  # --- Configuración de Google Cloud Storage ---
  GS_BUCKET_NAME: "media-supercolegios-plataforma"

  # --- Configuración de Django ---
  # Es importante que DEBUG sea 'False' en producción
  DEBUG: "False"

# Configuración para el punto de entrada de la aplicación (servidor Gunicorn)
entrypoint: gunicorn -b :$PORT config.wsgi

# Se añade esta sección para declarar explícitamente la conexión a Cloud SQL.
# Es la práctica recomendada y asegura que App Engine configure el socket correctamente.
beta_settings:
  cloud_sql_instances: "supercolegios:us-central1:mcolegio-db-prod"

# Configuración para instancias automáticas (puedes ajustarla más adelante)
instance_class: F1
automatic_scaling:
  max_instances: 2
  min_instances: 0
  target_cpu_utilization: 0.65
