# Generated by Django 5.2.3 on 2025-07-19 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaValoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_desempeno', models.CharField(max_length=50, verbose_name='Nombre del Desempeño (e.g., Bajo, Superior)')),
                ('valor_minimo', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Valor Mínimo')),
                ('valor_maximo', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Valor Máximo')),
                ('mensaje_boletin', models.TextField(blank=True, help_text='Mensaje opcional para mostrar en el boletín para este rango de notas.')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escala_valoracion', to='notas.colegio')),
            ],
            options={
                'verbose_name': 'Escala de Valoración',
                'verbose_name_plural': 'Escalas de Valoración',
                'ordering': ['valor_minimo'],
                'unique_together': {('colegio', 'nombre_desempeno')},
            },
        ),
    ]
