# Generated by Django 5.2.1 on 2025-07-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegio',
            name='nit',
            field=models.CharField(blank=True, max_length=60, verbose_name='NIT del Colegio'),
        ),
    ]
