# Generated by Django 5.2.1 on 2025-07-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colegio',
            old_name='direccion_fisica',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='colegio',
            old_name='telefono_contacto',
            new_name='telefono',
        ),
        migrations.AddField(
            model_name='colegio',
            name='color_fondo',
            field=models.CharField(default='#F8F9FA', help_text='Color de fondo general de las páginas', max_length=7),
        ),
        migrations.AddField(
            model_name='colegio',
            name='color_texto_primario',
            field=models.CharField(default='#FFFFFF', help_text='Color del texto sobre el color primario (ej. en botones)', max_length=7),
        ),
        migrations.AddField(
            model_name='colegio',
            name='escudo',
            field=models.ImageField(blank=True, help_text='Escudo para usar como marca de agua en PDFs', null=True, upload_to='logos_colegios/'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Icono para la pestaña del navegador (32x32px)', null=True, upload_to='logos_colegios/'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='historia',
            field=models.TextField(blank=True, null=True, verbose_name='Historia / Quiénes Somos'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='lema',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lema o Slogan'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='color_primario',
            field=models.CharField(default='#923E2B', max_length=7, verbose_name='Color Primario (Botones, Encabezados)'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='color_secundario',
            field=models.CharField(default='#4F4F4F', max_length=7, verbose_name='Color Secundario (Acentos)'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_colegios/', verbose_name='Logo Principal (PNG transparente recomendado)'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='logo_secundario',
            field=models.ImageField(blank=True, null=True, upload_to='logos_colegios/', verbose_name='Logo Secundario (ej. Gobernación)'),
        ),
    ]
