# Generated by Django 5.2.3 on 2025-07-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_escalavaloracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalavaloracion',
            name='valor_maximo',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Valor Máximo'),
        ),
        migrations.AlterField(
            model_name='escalavaloracion',
            name='valor_minimo',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Valor Mínimo'),
        ),
    ]
