# Generated by Django 5.2.1 on 2025-06-15 02:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_crear_grupos_iniciales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignaciondocente',
            options={'ordering': ['curso__nombre', 'materia__nombre'], 'verbose_name': 'Asignación Académica', 'verbose_name_plural': 'Asignaciones Académicas'},
        ),
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ['-fecha', 'estudiante'], 'verbose_name': 'Registro de Asistencia', 'verbose_name_plural': 'Registros de Asistencia'},
        ),
        migrations.AlterModelOptions(
            name='calificacion',
            options={'verbose_name': 'Calificación', 'verbose_name_plural': 'Calificaciones'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['nombre'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='docente',
            options={'ordering': ['user__last_name', 'user__first_name'], 'verbose_name': 'Docente', 'verbose_name_plural': 'Docentes'},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['user__last_name', 'user__first_name'], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['area__nombre', 'nombre'], 'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.AlterModelOptions(
            name='periodoacademico',
            options={'ordering': ['-ano_lectivo', 'fecha_inicio'], 'verbose_name': 'Periodo Académico', 'verbose_name_plural': 'Periodos Académicos'},
        ),
        migrations.AlterModelOptions(
            name='plandemejoramiento',
            options={'verbose_name': 'Plan de Mejoramiento', 'verbose_name_plural': 'Planes de Mejoramiento'},
        ),
        migrations.AlterModelOptions(
            name='reporteparcial',
            options={'verbose_name': 'Reporte Parcial', 'verbose_name_plural': 'Reportes Parciales'},
        ),
        migrations.RemoveField(
            model_name='docente',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='primer_apellido',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='segundo_apellido',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='celular_estudiante',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='celular_madre',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='celular_padre',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='colegio_anterior',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='compromiso_estudiante',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='compromiso_padre_familia',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='correo_electronico_contacto',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='direccion_residencia',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='documento_madre',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='documento_padre',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='enfermedades_alergias',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='eps',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='espera_en_porteria',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='grado_anterior',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='grupo_sanguineo',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='lugar_expedicion_documento',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='lugar_nacimiento',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='nombre_acudiente',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='nombre_madre',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='nombre_padre',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='numero_documento',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='primer_apellido',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='rh',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='segundo_apellido',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='telefono_acudiente',
        ),
        migrations.RemoveField(
            model_name='plandemejoramiento',
            name='fecha_limite',
        ),
        migrations.RemoveField(
            model_name='reporteparcial',
            name='observacion_adicional',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='¿Estudiante Activo?'),
        ),
        migrations.AddField(
            model_name='periodoacademico',
            name='nivelaciones_activas',
            field=models.BooleanField(default=False, help_text='Habilita el registro de notas finales de planes de mejoramiento para este periodo.', verbose_name='Nivelaciones Activas'),
        ),
        migrations.AddField(
            model_name='periodoacademico',
            name='reporte_parcial_activo',
            field=models.BooleanField(default=True, help_text='Indica si los docentes pueden registrar el reporte parcial de dificultades.', verbose_name='Reporte Parcial Activo'),
        ),
        migrations.AddField(
            model_name='plandemejoramiento',
            name='finalizado_por_admin',
            field=models.BooleanField(default=False, help_text='Marcar si la nota ya fue actualizada por el administrador.'),
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.docente', verbose_name='Docente'),
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='intensidad_horaria_semanal',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Intensidad Horaria (IH)'),
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.materia', verbose_name='Materia'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.asignaciondocente'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente'), ('T', 'Tarde')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.estudiante'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='justificada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.docente'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='es_recuperada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.estudiante'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.materia'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.periodoacademico'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='tipo_nota',
            field=models.CharField(choices=[('SER', 'Ser'), ('SABER', 'Saber'), ('HACER', 'Hacer'), ('PROM_PERIODO', 'Promedio Periodo')], max_length=15),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='valor_nota',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='inasistenciasmanualesperiodo',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='indicadorlogroperiodo',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.asignaciondocente'),
        ),
        migrations.AlterField(
            model_name='indicadorlogroperiodo',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='indicadorlogroperiodo',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.periodoacademico'),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='asignacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notas.asignaciondocente'),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='docente_reporta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notas.docente'),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.estudiante'),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notas.periodoacademico'),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='ano_lectivo',
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='esta_activo',
            field=models.BooleanField(default=True, help_text='Indica si los docentes pueden ingresar o modificar notas en este periodo.', verbose_name='Ingreso de Notas Activo'),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='nombre',
            field=models.CharField(choices=[('PRIMERO', 'Primer Periodo'), ('SEGUNDO', 'Segundo Periodo'), ('TERCERO', 'Tercer Periodo'), ('CUARTO', 'Cuarto Periodo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plandemejoramiento',
            name='descripcion_plan',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plandemejoramiento',
            name='nota_recuperacion',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='reporteparcial',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.asignaciondocente'),
        ),
        migrations.AlterField(
            model_name='reporteparcial',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.estudiante'),
        ),
        migrations.AlterField(
            model_name='reporteparcial',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.periodoacademico'),
        ),
        migrations.AlterField(
            model_name='reporteparcial',
            name='presenta_dificultades',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('estudiante', 'materia', 'periodo', 'tipo_nota')},
        ),
    ]
