# Generated by Django 5.2.3 on 2025-07-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_alter_escalavaloracion_valor_maximo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='max_materias_reprobadas',
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='max_areas_reprobadas',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Máximo de áreas reprobadas para ser promovido'),
        ),
    ]
