# Generated by Django 5.2.3 on 2025-06-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_alter_asignaciondocente_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_materias_reprobadas', models.PositiveSmallIntegerField(default=2, help_text='Un estudiante con MÁS de este número de materias reprobadas no será promovido.', verbose_name='Máximo de materias reprobadas para ser promovido')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ['-fecha', 'estudiante__user__last_name'], 'verbose_name': 'Registro de Asistencia', 'verbose_name_plural': 'Registros de Asistencia'},
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='esta_activo',
            field=models.BooleanField(default=True, help_text='Controla si los docentes pueden ingresar o modificar notas.', verbose_name='Ingreso de Notas Activo'),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='reporte_parcial_activo',
            field=models.BooleanField(default=True, help_text='Controla si los docentes pueden registrar el reporte parcial de dificultades.', verbose_name='Reporte Parcial Activo'),
        ),
    ]
