# Generated by Django 5.2.3 on 2025-07-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0004_remove_configuracionsistema_max_materias_reprobadas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colegio',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='colegio',
            name='logo_secundario',
        ),
        migrations.AddField(
            model_name='colegio',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='dane',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código DANE'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='linea_encabezado_1',
            field=models.CharField(blank=True, help_text='Ej: Nombre de la Institución', max_length=255, null=True, verbose_name='Línea 1 del Encabezado'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='linea_encabezado_2',
            field=models.CharField(blank=True, help_text='Ej: Resolución de Aprobación y NIT', max_length=255, null=True, verbose_name='Línea 2 del Encabezado'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='linea_encabezado_3',
            field=models.CharField(blank=True, help_text='Ej: Lema o Dirección', max_length=255, null=True, verbose_name='Línea 3 del Encabezado'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='linea_encabezado_4',
            field=models.CharField(blank=True, help_text='Ej: Ciudad y Departamento', max_length=255, null=True, verbose_name='Línea 4 del Encabezado'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='logo_derecho',
            field=models.ImageField(blank=True, help_text='Ej: Logo de la Gobernación', null=True, upload_to='logos_colegios/', verbose_name='Logo Derecho (Reportes)'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='logo_izquierdo',
            field=models.ImageField(blank=True, help_text='Ej: Logo del Colegio', null=True, upload_to='logos_colegios/', verbose_name='Logo Izquierdo (Reportes)'),
        ),
    ]
