# Generated by Django 5.2.1 on 2025-06-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0005_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='eliminado_por_destinatario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='eliminado_por_remitente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
    ]
