# Generated by Django 5.2.3 on 2025-07-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0005_remove_colegio_logo_remove_colegio_logo_secundario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='encabezado_pdf_sin_bordes',
            field=models.BooleanField(default=False, help_text='Marcar si el encabezado debe ocupar todo el ancho sin bordes (diseño especial).', verbose_name='Quitar bordes del encabezado en PDF'),
        ),
    ]
