# Generated by Django 5.2.1 on 2025-06-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0006_mensaje_eliminado_por_destinatario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='max_materias_reprobadas',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Máximo de materias reprobadas para ser promovido'),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='esta_activo',
            field=models.BooleanField(default=True, verbose_name='Ingreso de Notas Activo'),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='nivelaciones_activas',
            field=models.BooleanField(default=False, verbose_name='Nivelaciones Activas'),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='reporte_parcial_activo',
            field=models.BooleanField(default=True, verbose_name='Reporte Parcial Activo'),
        ),
    ]
