# Generated by Django 5.2.3 on 2025-07-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0006_colegio_encabezado_pdf_sin_bordes'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='linea_encabezado_1_fuente',
            field=models.CharField(choices=[('Helvetica', 'Helvetica (Recomendada)'), ('Arial', 'Arial'), ('Times New Roman', 'Times New Roman'), ('Courier', 'Courier'), ('Verdana', 'Verdana')], default='Helvetica', max_length=50, verbose_name='Fuente L1'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='linea_encabezado_1_tamano',
            field=models.PositiveSmallIntegerField(default=11, verbose_name='Tamaño L1 (pt)'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='linea_encabezado_2_fuente',
            field=models.CharField(choices=[('Helvetica', 'Helvetica (Recomendada)'), ('Arial', 'Arial'), ('Times New Roman', 'Times New Roman'), ('Courier', 'Courier'), ('Verdana', 'Verdana')], default='Helvetica', max_length=50, verbose_name='Fuente L2'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='linea_encabezado_2_tamano',
            field=models.PositiveSmallIntegerField(default=8, verbose_name='Tamaño L2 (pt)'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='linea_encabezado_3_fuente',
            field=models.CharField(choices=[('Helvetica', 'Helvetica (Recomendada)'), ('Arial', 'Arial'), ('Times New Roman', 'Times New Roman'), ('Courier', 'Courier'), ('Verdana', 'Verdana')], default='Helvetica', max_length=50, verbose_name='Fuente L3'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='linea_encabezado_3_tamano',
            field=models.PositiveSmallIntegerField(default=8, verbose_name='Tamaño L3 (pt)'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='linea_encabezado_4_fuente',
            field=models.CharField(choices=[('Helvetica', 'Helvetica (Recomendada)'), ('Arial', 'Arial'), ('Times New Roman', 'Times New Roman'), ('Courier', 'Courier'), ('Verdana', 'Verdana')], default='Helvetica', max_length=50, verbose_name='Fuente L4'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='linea_encabezado_4_tamano',
            field=models.PositiveSmallIntegerField(default=8, verbose_name='Tamaño L4 (pt)'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='linea_encabezado_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Línea 1 del Encabezado'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='linea_encabezado_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Línea 2 del Encabezado'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='linea_encabezado_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Línea 3 del Encabezado'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='linea_encabezado_4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Línea 4 del Encabezado'),
        ),
    ]
