# Generated by Django 5.2.3 on 2025-07-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0007_colegio_linea_encabezado_1_fuente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='linea_encabezado_1_cursiva',
            field=models.BooleanField(default=False, verbose_name='Cursiva L1'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='linea_encabezado_1_negrilla',
            field=models.BooleanField(default=True, verbose_name='Negrilla L1'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='linea_encabezado_1_subrayado',
            field=models.BooleanField(default=False, verbose_name='Subrayado L1'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='linea_encabezado_2_cursiva',
            field=models.BooleanField(default=False, verbose_name='Cursiva L2'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='linea_encabezado_2_negrilla',
            field=models.BooleanField(default=False, verbose_name='Negrilla L2'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='linea_encabezado_2_subrayado',
            field=models.BooleanField(default=False, verbose_name='Subrayado L2'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='linea_encabezado_3_cursiva',
            field=models.BooleanField(default=False, verbose_name='Cursiva L3'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='linea_encabezado_3_negrilla',
            field=models.BooleanField(default=False, verbose_name='Negrilla L3'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='linea_encabezado_3_subrayado',
            field=models.BooleanField(default=False, verbose_name='Subrayado L3'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='linea_encabezado_4_cursiva',
            field=models.BooleanField(default=False, verbose_name='Cursiva L4'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='linea_encabezado_4_negrilla',
            field=models.BooleanField(default=False, verbose_name='Negrilla L4'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='linea_encabezado_4_subrayado',
            field=models.BooleanField(default=False, verbose_name='Subrayado L4'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='linea_encabezado_1_fuente',
            field=models.CharField(choices=[('Helvetica', 'Helvetica (Estándar)'), ('Arial', 'Arial'), ('Times New Roman', 'Times New Roman'), ('Courier', 'Courier (Máquina de escribir)'), ('Verdana', 'Verdana'), ('Georgia', 'Georgia'), ('Garamond', 'Garamond'), ('Game On_PersonalUseOnly', 'Game On (Personalizada)')], default='Helvetica', max_length=100, verbose_name='Fuente L1'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='linea_encabezado_2_fuente',
            field=models.CharField(choices=[('Helvetica', 'Helvetica (Estándar)'), ('Arial', 'Arial'), ('Times New Roman', 'Times New Roman'), ('Courier', 'Courier (Máquina de escribir)'), ('Verdana', 'Verdana'), ('Georgia', 'Georgia'), ('Garamond', 'Garamond'), ('Game On_PersonalUseOnly', 'Game On (Personalizada)')], default='Helvetica', max_length=100, verbose_name='Fuente L2'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='linea_encabezado_3_fuente',
            field=models.CharField(choices=[('Helvetica', 'Helvetica (Estándar)'), ('Arial', 'Arial'), ('Times New Roman', 'Times New Roman'), ('Courier', 'Courier (Máquina de escribir)'), ('Verdana', 'Verdana'), ('Georgia', 'Georgia'), ('Garamond', 'Garamond'), ('Game On_PersonalUseOnly', 'Game On (Personalizada)')], default='Helvetica', max_length=100, verbose_name='Fuente L3'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='linea_encabezado_4_fuente',
            field=models.CharField(choices=[('Helvetica', 'Helvetica (Estándar)'), ('Arial', 'Arial'), ('Times New Roman', 'Times New Roman'), ('Courier', 'Courier (Máquina de escribir)'), ('Verdana', 'Verdana'), ('Georgia', 'Georgia'), ('Garamond', 'Garamond'), ('Game On_PersonalUseOnly', 'Game On (Personalizada)')], default='Helvetica', max_length=100, verbose_name='Fuente L4'),
        ),
    ]
