# Generated by Django 5.2.1 on 2025-06-19 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0007_alter_configuracionsistema_max_materias_reprobadas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaEstudiante',
            fields=[
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ficha', serialize=False, to='notas.estudiante')),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('eps', models.CharField(blank=True, max_length=100, verbose_name='EPS')),
                ('grupo_sanguineo', models.CharField(blank=True, max_length=5)),
                ('enfermedades_alergias', models.TextField(blank=True, verbose_name='Enfermedades o Alergias')),
                ('nombre_padre', models.CharField(blank=True, max_length=200)),
                ('celular_padre', models.CharField(blank=True, max_length=20)),
                ('nombre_madre', models.CharField(blank=True, max_length=200)),
                ('celular_madre', models.CharField(blank=True, max_length=20)),
                ('nombre_acudiente', models.CharField(blank=True, max_length=200)),
                ('celular_acudiente', models.CharField(blank=True, max_length=20)),
                ('email_acudiente', models.EmailField(blank=True, max_length=254)),
                ('espera_en_porteria', models.BooleanField(default=False)),
                ('colegio_anterior', models.CharField(blank=True, max_length=200)),
                ('grado_anterior', models.CharField(blank=True, max_length=20)),
                ('compromiso_padre', models.TextField(blank=True, verbose_name='Compromiso del Padre/Acudiente')),
                ('compromiso_estudiante', models.TextField(blank=True, verbose_name='Compromiso del Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroObservador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_suceso', models.DateField(verbose_name='Fecha del Suceso')),
                ('tipo', models.CharField(choices=[('ACADEMICA', 'Académica'), ('COMPORTAMENTAL', 'Comportamental')], max_length=15)),
                ('subtipo', models.CharField(blank=True, choices=[('POSITIVA', 'Positiva'), ('NEGATIVA', 'A Mejorar')], help_text='Solo para observaciones de comportamiento', max_length=10, null=True)),
                ('descripcion', models.TextField(verbose_name='Descripción del Suceso (Docente)')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('descargo_estudiante', models.TextField(blank=True, null=True, verbose_name='Descargo del Estudiante')),
                ('fecha_descargo', models.DateTimeField(blank=True, null=True)),
                ('notificado_a_estudiante', models.BooleanField(default=False)),
                ('docente_reporta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_hechas', to='notas.docente')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_observador', to='notas.estudiante')),
            ],
            options={
                'verbose_name': 'Registro del Observador',
                'verbose_name_plural': 'Registros del Observador',
                'ordering': ['-fecha_suceso'],
            },
        ),
    ]
