# Generated by Django 5.2.3 on 2025-07-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0008_colegio_linea_encabezado_1_cursiva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='alto_logos_pdf',
            field=models.PositiveSmallIntegerField(default=65, help_text='Ajusta la altura de los logos para que se alineen con el texto del encabezado.', verbose_name='Altura Máxima de Logos en PDF (px)'),
        ),
    ]
