# Generated by Django 5.2.1 on 2025-06-19 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0008_fichaestudiante_registroobservador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('MENSAJE', 'Nuevo Mensaje'), ('OBSERVADOR', 'Observación Registrada'), ('PERIODO', 'Cambio en Periodo'), ('RENDIMIENTO', 'Alerta de Rendimiento'), ('GENERAL', 'Aviso General')], default='GENERAL', max_length=15)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.DeleteModel(
            name='RegistroObservador',
        ),
    ]
