# Generated by Django 5.2.3 on 2025-07-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0009_colegio_alto_logos_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('PRE', 'Preescolar'), ('PRI', 'Primaria'), ('BAS', 'Básica Secundaria'), ('MED', 'Media')], default='PRI', max_length=4, verbose_name='Nivel Escolar'),
        ),
    ]
