# Generated by Django 5.2.1 on 2025-06-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0010_registroobservador'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaestudiante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_estudiantes/', verbose_name='Foto del Estudiante'),
        ),
    ]
