# Generated by Django 5.2.3 on 2025-07-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0010_curso_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='color_footer',
            field=models.CharField(default='#212529', max_length=7, verbose_name='Color de Fondo Pie de Página'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='color_footer_texto',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Color de Texto Pie de Página'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='color_topbar',
            field=models.CharField(default='#343A40', max_length=7, verbose_name='Color de Fondo Barra Superior/Lateral'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='color_topbar_texto',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Color de Texto Barra Superior/Lateral'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='layout_portal',
            field=models.CharField(choices=[('topbar', 'Diseño Clásico (Barra de Navegación Superior)'), ('sidebar', 'Diseño Moderno (Barra de Navegación Lateral)')], default='topbar', max_length=10, verbose_name='Diseño del Portal'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='mision',
            field=models.TextField(blank=True, null=True, verbose_name='Misión'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='modelo_pedagogico',
            field=models.TextField(blank=True, null=True, verbose_name='Modelo Pedagógico'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='vision',
            field=models.TextField(blank=True, null=True, verbose_name='Visión'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='color_primario',
            field=models.CharField(default='#0D6EFD', max_length=7, verbose_name='Color Primario (Botones, Acentos)'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='color_secundario',
            field=models.CharField(default='#6C757D', max_length=7, verbose_name='Color Secundario (Textos sutiles)'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='escudo',
            field=models.ImageField(blank=True, help_text='Escudo para el portal y marca de agua en PDFs', null=True, upload_to='logos_colegios/', verbose_name='Logo/Escudo Principal del Portal'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('PRE', 'Preescolar'), ('PRI', 'Primaria'), ('BAS', 'Básica Secundaria'), ('MED', 'Media')], default='BAS', max_length=4, verbose_name='Nivel Escolar'),
        ),
    ]
