# Generated by Django 5.2.1 on 2025-06-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0011_fichaestudiante_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='estado',
            field=models.CharField(choices=[('ENVIADO', 'Enviado'), ('BORRADOR', 'Borrador')], default='ENVIADO', max_length=10, verbose_name='Estado del Mensaje'),
        ),
    ]
