# Generated by Django 5.2.3 on 2025-07-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0011_colegio_color_footer_colegio_color_footer_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='es_recuperada',
            field=models.BooleanField(default=False, help_text='Indica si esta calificación de periodo fue recuperada con una nivelación.'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='tipo_nota',
            field=models.CharField(choices=[('SER', 'Promedio Ser'), ('SABER', 'Promedio Saber'), ('HACER', 'Promedio Hacer'), ('PROM_PERIODO', 'Promedio del Periodo'), ('NIVELACION', 'Nota de Nivelación')], max_length=12),
        ),
    ]
