# Generated by Django 5.2.1 on 2025-06-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0012_mensaje_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='abreviatura',
            field=models.CharField(blank=True, help_text='Abreviatura para reportes (ej: MAT, C.NAT)', max_length=10, verbose_name='Abreviatura'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='valor_nota',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
