# Generated by Django 5.2.1 on 2025-06-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0013_materia_abreviatura_alter_calificacion_valor_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='tipo_nota',
            field=models.CharField(choices=[('SER', 'Ser'), ('SABER', 'Saber'), ('HACER', 'Hacer'), ('PROM_PERIODO', 'Promedio Periodo'), ('NIVELACION', 'Nota de Nivelación')], max_length=15),
        ),
    ]
