# Generated by Django 5.2.1 on 2025-06-23 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0014_alter_calificacion_tipo_nota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacionBoletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('esta_visible', models.BooleanField(default=False, verbose_name='¿Visible para Estudiantes?')),
                ('periodo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notas.periodoacademico', verbose_name='Periodo Publicado')),
                ('publicado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Publicado por')),
            ],
            options={
                'verbose_name': 'Publicación de Boletín',
                'verbose_name_plural': 'Publicaciones de Boletines',
                'ordering': ['-periodo__ano_lectivo', '-periodo__fecha_inicio'],
            },
        ),
    ]
