# Generated by Django 5.2.1 on 2025-06-23 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0015_publicacionboletin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacionboletin',
            options={'ordering': ['-periodo__ano_lectivo', '-periodo__fecha_inicio'], 'verbose_name': 'Publicación de Boletín de Periodo', 'verbose_name_plural': 'Publicaciones de Boletines de Periodo'},
        ),
        migrations.CreateModel(
            name='PublicacionBoletinFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_lectivo', models.PositiveIntegerField(unique=True, verbose_name='Año Lectivo Publicado')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('esta_visible', models.BooleanField(default=False, verbose_name='¿Visible para Estudiantes?')),
                ('publicado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Publicado por')),
            ],
            options={
                'verbose_name': 'Publicación de Boletín Final',
                'verbose_name_plural': 'Publicaciones de Boletines Finales',
                'ordering': ['-ano_lectivo'],
            },
        ),
    ]
