# Generated by Django 5.2.1 on 2025-06-24 17:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0016_alter_publicacionboletin_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Documento')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción Breve')),
                ('archivo', models.FileField(upload_to='documentos_publicos/', verbose_name='Archivo (PDF, Word, etc.)')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Publicación')),
            ],
            options={
                'verbose_name': 'Documento Público',
                'verbose_name_plural': 'Documentos Públicos',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
