# Generated by Django 5.2.1 on 2025-06-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0019_noticia_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaestudiante',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de Documento'),
        ),
    ]
