# Generated by Django 5.2.1 on 2025-06-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0021_rename_documento_fichaestudiante_numero_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='intensidad_horaria',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Intensidad Horaria General (I.H.)'),
        ),
    ]
