# Generated by Django 5.2.1 on 2025-06-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0022_materia_intensidad_horaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenCarrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Texto grande que aparece sobre la imagen (opcional).', max_length=100)),
                ('subtitulo', models.CharField(blank=True, help_text='Texto más pequeño debajo del título (opcional).', max_length=200)),
                ('imagen', models.ImageField(upload_to='carrusel_portal/', verbose_name='Imagen de fondo')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Use números bajos para que aparezca primero (ej: 0, 1, 2...).')),
                ('visible', models.BooleanField(default=True, verbose_name='¿Visible en el portal?')),
            ],
            options={
                'verbose_name': 'Imagen del Carrusel',
                'verbose_name_plural': 'Imágenes del Carrusel',
                'ordering': ['orden'],
            },
        ),
        migrations.RemoveField(
            model_name='materia',
            name='intensidad_horaria',
        ),
        migrations.AlterField(
            model_name='materia',
            name='abreviatura',
            field=models.CharField(blank=True, help_text='Abreviatura para reportes (ej: MAT, C.NAT)', max_length=10, null=True, verbose_name='Abreviatura'),
        ),
    ]
