# Generated by Django 5.2.1 on 2025-06-30 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0023_imagencarrusel_remove_materia_intensidad_horaria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaDocente',
            fields=[
                ('docente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ficha', serialize=False, to='notas.docente')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de Contacto')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección de Residencia')),
                ('titulo_profesional', models.CharField(blank=True, max_length=200, verbose_name='Título Profesional')),
            ],
            options={
                'verbose_name': 'Ficha del Docente',
                'verbose_name_plural': 'Fichas de Docentes',
            },
        ),
    ]
