# Generated by Django 5.2.1 on 2025-06-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0024_fichadocente'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadocente',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de Documento'),
        ),
    ]
