# Generated by Django 5.2.1 on 2025-07-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0025_fichadocente_numero_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadocente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='docentes/fotos/'),
        ),
    ]
