# Generated by Django 5.2.1 on 2025-07-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0026_fichadocente_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadocente',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección de Residencia'),
        ),
        migrations.AlterField(
            model_name='fichadocente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_docentes/', verbose_name='Foto del Docente'),
        ),
        migrations.AlterField(
            model_name='fichadocente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto'),
        ),
        migrations.AlterField(
            model_name='fichadocente',
            name='titulo_profesional',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título Profesional'),
        ),
        migrations.AlterField(
            model_name='fichaestudiante',
            name='celular_acudiente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fichaestudiante',
            name='celular_madre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fichaestudiante',
            name='celular_padre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fichaestudiante',
            name='colegio_anterior',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fichaestudiante',
            name='compromiso_estudiante',
            field=models.TextField(blank=True, null=True, verbose_name='Compromiso del Estudiante'),
        ),
        migrations.AlterField(
            model_name='fichaestudiante',
            name='compromiso_padre',
            field=models.TextField(blank=True, null=True, verbose_name='Compromiso del Padre/Acudiente'),
        ),
        migrations.AlterField(
            model_name='fichaestudiante',
            name='email_acudiente',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='fichaestudiante',
            name='enfermedades_alergias',
            field=models.TextField(blank=True, null=True, verbose_name='Enfermedades o Alergias'),
        ),
        migrations.AlterField(
            model_name='fichaestudiante',
            name='eps',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='EPS'),
        ),
        migrations.AlterField(
            model_name='fichaestudiante',
            name='grado_anterior',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fichaestudiante',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True, verbose_name='Grupo Sanguíneo y RH'),
        ),
        migrations.AlterField(
            model_name='fichaestudiante',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fichaestudiante',
            name='nombre_acudiente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fichaestudiante',
            name='nombre_madre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fichaestudiante',
            name='nombre_padre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
