# Generated by Django 5.2.1 on 2025-07-09 02:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0028_alter_calificacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='porcentaje_hacer',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje HACER por defecto'),
        ),
        migrations.AddField(
            model_name='materia',
            name='porcentaje_saber',
            field=models.PositiveIntegerField(default=40, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje SABER por defecto'),
        ),
        migrations.AddField(
            model_name='materia',
            name='porcentaje_ser',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje SER por defecto'),
        ),
        migrations.AddField(
            model_name='materia',
            name='usar_ponderacion_equitativa',
            field=models.BooleanField(default=True, help_text='Si se marca, las nuevas asignaciones de esta materia usarán 33.33% para cada competencia.', verbose_name='Usar ponderación equitativa por defecto'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='abreviatura',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Abreviatura'),
        ),
    ]
