# Generated by Django 5.2.1 on 2025-07-11 01:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0029_materia_porcentaje_hacer_materia_porcentaje_saber_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCalificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente_puede_modificar', models.BooleanField(default=False, help_text="Si se activa, cada docente podrá ajustar los porcentajes para sus propias asignaturas desde la vista de 'Ingresar Notas'.", verbose_name='Permitir que los docentes modifiquen los porcentajes de calificación')),
            ],
            options={
                'verbose_name': 'Configuración de Permisos de Calificación',
                'verbose_name_plural': 'Configuración de Permisos de Calificación',
            },
        ),
        migrations.AlterField(
            model_name='imagencarrusel',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imagencarrusel',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='imagencarrusel',
            name='titulo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='imagencarrusel',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado')], default='BORRADOR', max_length=10),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='resumen',
            field=models.CharField(max_length=500, verbose_name='Resumen Corto'),
        ),
    ]
