# Generated by Django 5.2.1 on 2025-07-11 20:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0030_configuracioncalificaciones_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['nombre'], 'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.RemoveField(
            model_name='materia',
            name='area',
        ),
        migrations.CreateModel(
            name='PonderacionAreaMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_porcentual', models.DecimalField(decimal_places=2, help_text='El peso que esta materia tiene sobre la nota final del área. Ej: 40.00', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Peso Porcentual (%)')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.areaconocimiento')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.materia')),
            ],
            options={
                'verbose_name': 'Ponderación de Materia en Área',
                'verbose_name_plural': 'Ponderaciones de Materias en Áreas',
                'unique_together': {('area', 'materia')},
            },
        ),
        migrations.AddField(
            model_name='areaconocimiento',
            name='materias',
            field=models.ManyToManyField(related_name='areas_ponderadas', through='notas.PonderacionAreaMateria', to='notas.materia'),
        ),
    ]
