# Generated by Django 5.2.1 on 2025-07-12 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0031_alter_materia_options_remove_materia_area_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaconocimiento',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del Área'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del Curso'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la Materia'),
        ),
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre del Colegio')),
                ('slug', models.SlugField(blank=True, help_text='Identificador para la URL (se genera automáticamente)', max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_colegios/', verbose_name='Logo del Colegio')),
                ('color_primario', models.CharField(default='#0d6efd', max_length=7, verbose_name='Color Primario')),
                ('color_secundario', models.CharField(default='#6c757d', max_length=7, verbose_name='Color Secundario')),
                ('portal_publico_activo', models.BooleanField(default=True, verbose_name='¿Portal Público Activo?')),
                ('admin_general', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colegios_administrados', to=settings.AUTH_USER_MODEL, verbose_name='Administrador Principal')),
            ],
            options={
                'verbose_name': 'Colegio',
                'verbose_name_plural': 'Colegios',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='asignaciondocente',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='inasistenciasmanualesperiodo',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='periodoacademico',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='plandemejoramiento',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ponderacionareamateria',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='reporteparcial',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='areaconocimiento',
            name='colegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas_conocimiento', to='notas.colegio'),
        ),
        migrations.AddField(
            model_name='asignaciondocente',
            name='colegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_docentes', to='notas.colegio'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='colegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='notas.colegio'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='colegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='notas.colegio'),
        ),
        migrations.AddField(
            model_name='configuracioncalificaciones',
            name='colegio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_calificaciones', to='notas.colegio'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='colegio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='notas.colegio'),
        ),
        migrations.AddField(
            model_name='curso',
            name='colegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='notas.colegio'),
        ),
        migrations.AddField(
            model_name='docente',
            name='colegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docentes', to='notas.colegio'),
        ),
        migrations.AddField(
            model_name='documentopublico',
            name='colegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_publicos', to='notas.colegio'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='colegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='notas.colegio'),
        ),
        migrations.AddField(
            model_name='fotogaleria',
            name='colegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos_galeria', to='notas.colegio'),
        ),
        migrations.AddField(
            model_name='imagencarrusel',
            name='colegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_carrusel', to='notas.colegio'),
        ),
        migrations.AddField(
            model_name='inasistenciasmanualesperiodo',
            name='colegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inasistencias_manuales', to='notas.colegio'),
        ),
        migrations.AddField(
            model_name='indicadorlogroperiodo',
            name='colegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicadores_logro', to='notas.colegio'),
        ),
        migrations.AddField(
            model_name='materia',
            name='colegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='notas.colegio'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='colegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='notas.colegio'),
        ),
        migrations.AddField(
            model_name='notadetallada',
            name='colegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas_detalladas', to='notas.colegio'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='colegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='notas.colegio'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='colegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='notas.colegio'),
        ),
        migrations.AddField(
            model_name='observacion',
            name='colegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='notas.colegio'),
        ),
        migrations.AddField(
            model_name='periodoacademico',
            name='colegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodos_academicos', to='notas.colegio'),
        ),
        migrations.AddField(
            model_name='plandemejoramiento',
            name='colegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planes_mejoramiento', to='notas.colegio'),
        ),
        migrations.AddField(
            model_name='ponderacionareamateria',
            name='colegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ponderaciones', to='notas.colegio'),
        ),
        migrations.AddField(
            model_name='publicacionboletin',
            name='colegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones_boletines', to='notas.colegio'),
        ),
        migrations.AddField(
            model_name='publicacionboletinfinal',
            name='colegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones_finales', to='notas.colegio'),
        ),
        migrations.AddField(
            model_name='registroobservador',
            name='colegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_observador', to='notas.colegio'),
        ),
        migrations.AddField(
            model_name='reporteparcial',
            name='colegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes_parciales', to='notas.colegio'),
        ),
        migrations.AlterUniqueTogether(
            name='areaconocimiento',
            unique_together={('nombre', 'colegio')},
        ),
        migrations.AlterUniqueTogether(
            name='asignaciondocente',
            unique_together={('docente', 'materia', 'curso', 'colegio')},
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('estudiante', 'asignacion', 'fecha', 'colegio')},
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('estudiante', 'materia', 'periodo', 'tipo_nota', 'colegio')},
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('nombre', 'colegio')},
        ),
        migrations.AlterUniqueTogether(
            name='docente',
            unique_together={('user', 'colegio')},
        ),
        migrations.AlterUniqueTogether(
            name='estudiante',
            unique_together={('user', 'colegio')},
        ),
        migrations.AlterUniqueTogether(
            name='inasistenciasmanualesperiodo',
            unique_together={('estudiante', 'asignacion', 'periodo', 'colegio')},
        ),
        migrations.AlterUniqueTogether(
            name='materia',
            unique_together={('nombre', 'colegio')},
        ),
        migrations.AlterUniqueTogether(
            name='periodoacademico',
            unique_together={('nombre', 'ano_lectivo', 'colegio')},
        ),
        migrations.AlterUniqueTogether(
            name='plandemejoramiento',
            unique_together={('estudiante', 'asignacion', 'periodo_recuperado', 'colegio')},
        ),
        migrations.AlterUniqueTogether(
            name='ponderacionareamateria',
            unique_together={('area', 'materia', 'colegio')},
        ),
        migrations.AlterUniqueTogether(
            name='reporteparcial',
            unique_together={('estudiante', 'asignacion', 'periodo', 'colegio')},
        ),
    ]
