# Generated by Django 5.2.1 on 2025-07-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0032_alter_areaconocimiento_nombre_alter_curso_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='domain',
            field=models.CharField(blank=True, help_text='Ej: integradoapr.edu.co (sin www ni http://)', max_length=255, null=True, unique=True, verbose_name='Dominio Principal'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Email de Contacto'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono de Contacto'),
        ),
    ]
