# Generated by Django 5.2.1 on 2025-07-13 03:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0033_colegio_domain_colegio_email_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaciondocente',
            name='porcentaje_hacer',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='porcentaje_saber',
            field=models.PositiveIntegerField(default=40, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='porcentaje_ser',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='usar_ponderacion_equitativa',
            field=models.BooleanField(default=True, verbose_name='Usar ponderación equitativa'),
        ),
        migrations.AlterField(
            model_name='configuracioncalificaciones',
            name='docente_puede_modificar',
            field=models.BooleanField(default=False, verbose_name='Permitir que los docentes modifiquen los porcentajes de calificación'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='usar_ponderacion_equitativa',
            field=models.BooleanField(default=True, verbose_name='Usar ponderación equitativa por defecto'),
        ),
        migrations.AlterField(
            model_name='ponderacionareamateria',
            name='peso_porcentual',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Peso Porcentual (%)'),
        ),
    ]
